PHPBoost/PHPBoost

- kernel/lib/php/mathpublisher/mathpublisher.php
replace ereg and old style constructor
> [FIX] PHP7.0 compatibility

- cache/.htaccess
> [FIX] free compatibility

- kernel/framework/content/formatting/parser/ContentSecondParser.class.php
- lang/english/status-messages-common.php
- lang/french/status-messages-common.php
Added BBCode member/moderator
Ajout BBCode membre/moderateur
> [FEATURE] Balises BBCode member/moderator

- kernel/framework/phpboost/cache/HtaccessFileCache.class.php
fonctionnalité qui detect automatique si la personne est chez free.fr et ajoute "php56 1" au .htaccess
peut être que c'est "moche" mais cela semble bien fonctionner
feature to automatically detect free.fr and add the "php56 1" un the .htaccess
maybe it's "ugly" but seem to be working well
> [feature] automatically detect free.fr

- kernel/framework/content/formatting/parser/ContentSecondParser.class.php
Frençais :
Je pense que cette solution est mieux que de tout mettre en minuscule (cette fois c'est bien testé)
Anglais :
i think it's better solution than all in lowecase (this time is well tested)
> [FIX] feature [member] and [moderator]

- forum/membermsg.php
voilà mieux niveau message de commit
> [FIX] #1692 guest can see forum content even if they don't have the right

- forum/membermsg.php
le fix doit être horrible mais ça fait le job
> [FIX] guest can see forum content even if they don't have the right

- kernel/framework/phpboost/cache/HtaccessFileCache.class.php
> [FIX] for this **** of free

- kernel/lib/php/phpmailer/class.phpmailer.php
- kernel/lib/php/phpmailer/class.pop3.php
- kernel/lib/php/phpmailer/class.smtp.php
CVE-2016-10033 in PHPMailer, so update to 5.2.19 to fix it (fixed in 5.2.18).
> [FIX] CVE-2016-10033 in PHPMailer

- kernel/lib/php/phpmailer/class.phpmailer.php
- kernel/lib/php/phpmailer/class.pop3.php
- kernel/lib/php/phpmailer/class.smtp.php
official PHPmailer patch for CVE-2016-10033&CVE-2016-10045
> [FIX] CVE-2016-10033&CVE-2016-10045 in PHPMailer

- kernel/framework/core/environment/Environment.class.php
Check if function exist or is enable before using it
> [FIX] Check if exist/activated

- articles/services/Article.class.php
- download/services/DownloadFile.class.php
- news/services/News.class.php
- web/services/WebLink.class.php
bonne méthode ou mal compris ?
> [FIX] #1737 Lien "Lire la suite" dans les news

- kernel/framework/content/category/CategoriesCache.class.php
> [HOTFIX] #1739

- update/services/UpdateServices.class.php
Problème de Mise a jour version 5.0 vers 5.1 sur serveur Free
> [FIX] #1755

- admin/admin_groups.php
- kernel/framework/phpboost/cache/GroupsCache.class.php
Après un rapide test cela fix les 2 problème (affichage + génération variable JS)
Cf : https://www.phpboost.com/bugtracker/detail/1781 + https://www.phpboost.com/bugtracker/detail/1782
> [FIX] #1782 and #1781

- admin/config/controllers/AdminAdvancedConfigController.class.php
- kernel/framework/phpboost/cache/HtaccessFileCache.class.php
- kernel/framework/phpboost/config/ServerEnvironmentConfig.class.php
- lang/english/admin-config-common.php
- lang/french/admin-config-common.php
Select if the webmaster include or not subdomain for HSTS and cleanup/optimization of htaccess file.
> [FEATURE] HSTS subdomain + htaccess optimization

- kernel/framework/content/category/controllers/AbstractCategoriesManageController.class.php
- kernel/framework/io/http/HTTPRequestCustom.class.php
[FIX] #1812 HTTP_X_FORWARDED_FOR multiple IPs 
+
[FIX] #1811 Caractères spéciaux description catégorie
> [FIX] #1812 HTTP_X_FORWARDED_FOR multiple IPs && [FIX] #1811 Caractères spéciaux description catégorie

- news/lang/english/install.php
- news/lang/french/install.php
Génération de la news après install : pas les bons liens
> [FIX]#1819 Génération de la news après install

- kernel/framework/util/Url.class.php
Page 404 dans un sujet avec des guillemets français « et »
> [FIX] #1826

- lang/english/admin.php
- lang/french/admin.php
https://www.gnu.org/licenses/gpl-howto.html pour le texte de licence
https://www.gnu.org/licenses/gpl-howto.html for the license text
> Fix duplicate/missing and license (GNU GPL3 and not 2)

- kernel/lib/php/phpmailer/class.phpmailer.php
- kernel/lib/php/phpmailer/class.pop3.php
- kernel/lib/php/phpmailer/class.smtp.php
> [MAJ] PHPMailer update

- kernel/framework/phpboost/environment/ServerConfiguration.class.php
[FIX] Upload when memory_limit or post_max_size are unlimited
> [FIX] Upload specific config

- admin/themes/controllers/AdminThemesNotInstalledListController.class.php
Warning : Undefined array key 0
[0] /admin/themes/controllers/AdminThemesNotInstalledListController.class.php:245 [0] /admin/themes/controllers/AdminThemesNotInstalledListController.class.php:38 - AdminThemesNotInstalledListController->upload_theme() [1] /kernel/framework/mvc/dispatcher/UrlControllerMapper.class.php:72 - AdminThemesNotInstalledListController->execute() [2] /kernel/framework/mvc/dispatcher/UrlControllerMapper.class.php:44 - UrlControllerMapper->do_call() [3] /kernel/framework/mvc/dispatcher/Dispatcher.class.php:47 - UrlControllerMapper->call() [4] /kernel/framework/mvc/dispatcher/DispatchManager.class.php:26 - Dispatcher->dispatch() [5] /admin/themes/index.php:20 - DispatchManager::dispatch() [URL] /admin/themes/?url=/add/
Warning : Trying to access array offset on value …
> Fix AdminThemesNotInstalledListController.class.php

- kernel/framework/helper/FileSystemHelper.class.php
- kernel/framework/io/filesystem/File.class.php
[Issue #157 ](https://github.com/PHPBoost/PHPBoost/issues/157)
FIX for Auto update
Change CURL opt to lie to phpboost server (USER_AGENT)
Ignore Hash check
Checking by test original file size (by header request), downloaded bytes & size of the downloaded file
> FIX Auto Install UPD

- kernel/framework/helper/FileSystemHelper.class.php
- kernel/framework/io/filesystem/File.class.php
>  FIX Auto Install UPD

- kernel/framework/core/environment/Environment.class.php
- kernel/framework/phpboost/user/session/SessionData.class.php
Error Token on first login day
> [FIX] First login attempt

- gallery/controllers/GalleryDisplayCategoryController.class.php
- gallery/gallery_begin.php
https://www.phpboost.com/bugtracker/detail/2054-gallery-l-url-personnalisee-n-est-pas-prise-en-compte
> [FIX] Gallery Personnalized URL

- admin/cache/controllers/AdminCSSCacheController.class.php
- admin/cache/controllers/AdminCacheConfigController.class.php
- bugtracker/controllers/BugtrackerStatsListController.class.php
- bugtracker/lang/english/common.php
- bugtracker/lang/french/common.php
- bugtracker/phpboost/BugtrackerExtensionPointProvider.class.php
- bugtracker/templates/BugtrackerStatsListController.tpl
- cache/js/.htaccess
- kernel/cli/command/cache/CLIClearCacheCommand.class.php
- kernel/framework/helper/FileSystemHelper.class.php
- kernel/framework/io/data/cache/CacheService.class.php
- kernel/framework/io/optimization/JSCacheManager.class.php
- kernel/framework/io/optimization/JSFileOptimizer.class.php
- kernel/framework/phpboost/environment/AbstractDisplayGraphicalEnvironment.class.php
- kernel/framework/phpboost/module/Module.class.php
- kernel/framework/phpboost/module/js/ModuleJsFiles.class.php
- kernel/framework/phpboost/theme/ThemesManager.class.php
- kernel/framework/util/chart/BarChart.class.php
- kernel/framework/util/chart/Chart.class.php
- kernel/framework/util/chart/ChartDataset.class.php
- kernel/framework/util/chart/PieChart.class.php
- lang/english/admin-lang.php
- lang/french/admin-lang.php
- sandbox/phpboost/SandboxModuleMiniMenu.class.php
- stats/controllers/StatsDisplayController.class.php
- stats/services/StatsBarChart.class.php
- stats/services/StatsPieChart.class.php
- stats/update/StatsModuleUpdateVersion.class.php
- templates/__default__/framework/util/chart.tpl
[MAJ] Add JS Cache
Create .htaccess in cache/js
[MAJ] Bugtracker Chart stats
Headers & TPL vars name
[MAJ] Add FileSystemHelper get_remote_content_file
[FIX] Remove Autorizations from kernel-modules DB
> [MAJ] Add JS Cache

- gallery/controllers/GalleryDisplayCategoryController.class.php
https://www.phpboost.com/bugtracker/detail/2055-gallery-contenu-d-album-non-affiche
> [FIX] Gallery not displayed category when using numbers in title
